name: build
on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - run: |
          go build -ldflags "-w -s" -o ./build/ ./cmd/w3t 

      - uses: crazy-max/ghaction-upx@v2
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'
        with:
          version: latest
          files: |
            ./build/w3t*
          args: --best --lzma

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: w3t.exe
          path: ./build

      - uses: actions/upload-artifact@v3
        if: matrix.os != 'windows-latest'
        with:
          name: w3t
          path: ./build
